read1: "data/SP180627-from-flowcell-HJWMMBCX2-on-2018-07-06/Merge-sample-SP180627-from-flowcell-HJWMMBCX2-on-2018-07-06_Read_1_passed_filter.fastq.gz"
read2: "data/SP180627-from-flowcell-HJWMMBCX2-on-2018-07-06/Merge-sample-SP180627-from-flowcell-HJWMMBCX2-on-2018-07-06_Read_2_Index_Read_passed_filter.fastq.gz"
read3: "data/SP180627-from-flowcell-HJWMMBCX2-on-2018-07-06/Merge-sample-SP180627-from-flowcell-HJWMMBCX2-on-2018-07-06_Read_3_Index_Read_passed_filter.fastq.gz"
neb_barcodes_file: "barcodes/neb_barcodes.txt"
tagseq_barcodes_file: "barcodes/tagseq_barcodes.txt"
demultiplexed_dir: "data/SP180627-from-flowcell-HJWMMBCX2-on-2018-07-06/demultiplexed"
umi_labeled_dir: "data/SP180627-from-flowcell-HJWMMBCX2-on-2018-07-06/umi_labeled"
