name: lamaya_tn5_demultiplex
channels:
    - bioconda
    - conda-forge
    - defaults
dependencies:
    - snakemake=5.2.0
    - drmaa=0.7.8
    - pigz=2.4
    - umi_tools=0.5.4
    - pip:
      - barcode_splitter==0.18.2
